# Generated by Django 4.1.2 on 2022-10-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_image_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='devcom'),
        ),
    ]
