# Generated by Django 4.1.2 on 2022-11-10 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_followers_alter_profile_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followers',
            new_name='followedby',
        ),
    ]
