# Generated by Django 4.1.2 on 2022-11-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_followers_profile_followedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followedby',
            field=models.ManyToManyField(blank=True, related_name='followed', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follow', to='users.profile'),
        ),
    ]
