# Generated by Django 4.1.2 on 2022-11-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_followedby_alter_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followedby',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='users.profile'),
        ),
    ]
