# Generated by Django 4.1.2 on 2022-11-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followedby',
        ),
    ]
