# Generated by Django 4.1.2 on 2022-11-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_profile_followedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followedby',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='users.profile'),
        ),
    ]
