# Generated by Django 4.1.2 on 2022-10-24 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_following'),
        ('feed', '0002_alter_feed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='related_like', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='related_save', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='replies',
            name='commentator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
