# Generated by Django 4.1.2 on 2022-10-24 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_following'),
        ('feed', '0003_alter_feed_likes_alter_feed_saves_alter_feed_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='commentator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
