# Generated by Django 4.1.2 on 2022-10-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_replies_commentator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='user',
            new_name='profile',
        ),
    ]
