# Generated by Django 4.1.2 on 2022-11-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_avatar_alter_profile_cover_image'),
        ('feed', '0006_alter_feed_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replies',
            new_name='Comments',
        ),
    ]
