# Generated by Django 4.1.2 on 2022-11-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_comments_options_remove_comments_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='replies',
            new_name='reply',
        ),
    ]
