# Generated by Django 4.1.2 on 2022-11-18 14:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_rename_commentated_comments_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
