# Generated by Django 4.1.2 on 2022-11-19 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0018_alter_profile_avatar_alter_profile_cover_image'),
        ('feed', '0013_alter_feed_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('notification_type', models.CharField(choices=[('new_follower', 'new_follower'), ('new_comment', 'new_comment'), ('new_post', 'new_post')], max_length=18)),
                ('is_read', models.BooleanField(default=False)),
                ('from_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_noti', to='users.profile')),
                ('new_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.comments')),
                ('new_follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('new_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.feed')),
                ('to_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_to', to='users.profile')),
            ],
        ),
    ]
