# Generated by Django 4.1.2 on 2022-11-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifications_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='new_comment',
        ),
    ]
